/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package china.social.survey;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void alwaysPassing(){
        assertEquals(1, 1);
    }
}
